version: '3'
services:
  cookbookdb:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cookbook
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  cookbook-api:
    container_name: cookbook-api
    image: rpissarra/cookbook-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cookbookdb:5432/cookbook
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - cookbookdb
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: